function [dx] = gd10(u,v)
	du = e^u+v*e^(u*v)+2*u-2*v-3;
	dv = 2*e^(2*v)+u*e^(u*v)+4*v-2*u-2;
	de = [du;dv];
	duu = e^u+v^2*e^(u*v)+2;
	duv = e^(u*v)+u*v*e^(u*v)-2;
	dvv = 4*e^(2*v)+u^2*e^(u*v)+4;
	dee = [duu duv; duv dvv];
	dx = -dee^-1*de;